- admin/src/components/clinic_components/ClinicTable.jsx
- admin/src/components/csc_components/CscTable.jsx
- admin/src/components/lab_components/LabTable.jsx
- admin/src/components/shop_components/ShopTable.jsx
- admin/src/components/spa_components/SpaTable.jsx
> updated code

- admin/src/components/login_components/Login.jsx
We have changed the place holder name for password.
> fix(first-11)-We have changed the place holder name for password.

- admin/src/App.css
- admin/src/App.js
We have changed the background color of the left navigation bar and resolved the issue
> fix(FIRST-9)- No Text visibility after hovering on Left Navigation Bar

- admin/src/components/bus_components/BusTable.css
- admin/src/components/clinic_components/ClinicTable.css
- admin/src/components/csc_components/CscTable.css
- admin/src/components/lab_components/LabTable.css
- admin/src/components/shop_components/ShopTable.css
- admin/src/components/spa_components/SpaTable.css
I have made the changes with width of all the components under novaTable
> fix(FIRST-1) - Made changes with width of the novaTable

- admin/src/components/lab_components/LabTable.jsx
> Feature(FIRST-32) - Added Option to select days

- admin/src/components/lab_components/LabTable.jsx
Added the style display:"inline-flex" at line number 678 under LabTable.jsx.
> fix(FIRST-33) - Made services to be appear horizontally

- admin/src/App.js
- admin/src/components/consumer_components/consumermodule.jsx
Created new consumer account as per the requirement.
> feature(FIRST-34) - Added Create New Consumer Screen

- admin/src/components/consumer_components/consumermodule.css
- admin/src/components/consumer_components/consumermodule.jsx
Alignment issue on "New Consumer Window" is fixed.
> fix-(FIRST-42) - Alignment issue is fixed

- admin/src/components/lab_components/AvailableServices.css
- admin/src/components/lab_components/AvailableServices.js
- admin/src/components/lab_components/PatientDetails.js
- admin/src/components/login_components/Login.jsx
API Integration is done for service Summary
> API (FIRST- 70) - API Integration for Service Summary

- admin/src/App.css
- admin/src/App.js
I have added the Search bar on to Navbar with Lab Selection dropdown
> NOVACARD-96 (Design) - I have added the Search bar on to Navbar

- admin/src/components/consumers_appointments/PatientAppointmentsSummary.js.js
Adjusted the overflow to Scroll
> NOVACARD-97 (Fix) - Adjusted the overflow to Scroll

- admin/src/components/lab_components/LabTable.jsx
NOVACARD-91-(Bug-FIx) - Added a button to go back to the Lab Table screen
> NOVACARD-91(Bug-FIx) - Added a button to go back to the Lab Table screen

- admin/src/components/clinic_components/ClinicTable.jsx
NOVACARD-107 (Bug) - Made changes with the Title to delete Clinic.
Minor Change.
> NOVACARD-107 (Bug) - Made changes with the Title to delete Clinic

- admin/src/App.css
- admin/src/App.js
- admin/src/components/login_components/Login.css
Made changes with notification icons on top bar.
> NOVACARD-71 Made changes with notification icons on top bar. 

- admin/src/App.js
- admin/src/components/csc_components/CscTable.css
- admin/src/components/csc_components/CscTable.jsx
- admin/src/components/shop_components/ShopTable.css
- admin/src/components/shop_components/ShopTable.jsx
- admin/src/components/spa_components/SpaTable.css
- admin/src/components/spa_components/SpaTable.jsx
NOVACARD-84  SPA, Shaloon  and CSC are removed from navigation bar.
> NOVACARD-84  SPA, Shaloon  and CSC are removed from navigation bar.

- admin/src/components/consumers_appointments/LabTestResultsEntry.css
- admin/src/components/consumers_appointments/LabTestResultsEntry.js
- admin/src/components/consumers_appointments/PatientAppointmentsSummary.css
- admin/src/components/consumers_appointments/PatientAppointmentsSummary.js
NOVACARD-103(Design) - Designed Report entry screen.
> NOVACARD-103(Design) - Designed Report entry screen

- admin/package-lock.json
- admin/src/App.js
- admin/src/components/access-managment/AccessManagment.css
- admin/src/components/access-managment/AccessManagment.jsx
- admin/src/components/access-managment/MainComponent.js
Created access management Tab & dashboard with new buttons
> Access_Management

- admin/src/components/Dashboard_Components/Dashboard.css
- admin/src/components/Dashboard_Components/Dashboard.js
Dashboard Design has been completed.
> NOVACARD-105(DESIGN) - Designed dashboard

- admin/src/App.js
Added the Dashboard Component to App.js. In earlier commit 105, I forgot to add Dashboard Component.
> Added the Dashboard Component to App.js

- admin/src/components/IMS/Ims.js
- admin/src/components/ems_components/Ems.js
- admin/src/components/ems_components/Ems.jsx
- admin/src/components/promotions_offers/Createpromotions.js
Renamed the EMS.IMS & Create promotions table names
> Renaming the EMS table names

- admin/src/components/consumers_appointments/Notes.js
NOVACARD-155(Fix) - Made small change to clear the form field after the Save Note.
> NOVACARD-155(Fix) - Made small change to clear the form field after the Save Note.

- admin/src/components/ems_components/Ems.js
NOVACARD-138(Fix) - Modified the API name to make dynamic. Please Approve.
> NOVACARD-138(Fix) - Modified the API name to make dynamic. Please Approve.

- admin/src/components/access_management/AccessManagement.css
- admin/src/components/access_management/AccessManagement.js
I have added all available functionalities > Design is just half of the page > Either we can make it full screen or we will add some related section to the Right Side.
> NOCACARD_137_Access Management

- admin/src/App.js
I have changed Navigation Menu "Access Management" spellings as following:
{ label: "Access **Managemnt**", key: "/accessManagement" },
{ label: "Access **Management**", key: "/accessManagement" },
> NOVACARD-153-Access Management-Spelling-changed

- admin/src/components/login_components/Login.css
- admin/src/components/login_components/Login.jsx
I have re-arranged with login & password main screen buttons
> Login & Password Main screen Buttons

- admin/src/components/consumers_appointments/AppointmentBookingForm .js
NOVACARD-172(Fix-Bug) - Search Services Issue has been resolved under Book Appointment Screen
> NOVACARD-172(Fix-Bug) - Search Services Issue has been resolved under Book Appointment Screen

- admin/src/components/consumers_appointments/PatientAppointmentsSummary.js
- admin/src/components/consumers_appointments/PatientCurrentAppointments.js
AppointmentFix - Fixed the issues opening LabTestResults Modal.
> AppointmentFix - Fixed the issues opening LabTestResults Modal.

- admin/src/components/Dashboard_Components/Dashboard.css
- admin/src/components/Dashboard_Components/Dashboard.js
NOVACARD-145(API) - API Integration part is done for Appointment Counts for Adults, Kids and Extra Adults
> NOVACARD-145(API) - API Integration part is done for Appointment Counts for Adults, Kids and Extra Adults

- admin/src/components/consumer_components/consumermodule.jsx
(NOVACARD-166)(NOVACARD-167) - Made changes to calculate DOB on entering Age and to calculate Age on entering DOB.
> (NOVACARD-166)(NOVACARD-167) - Made changes to calculate DOB on entering Age and to calculate Age on entering DOB.

- admin/src/components/consumers_appointments/AppointmentBookingForm .js
Novacard-173(Fix) - Made changes with Appointment Booking Form to clear the input values OnClick of Book Appointment Button
> Novacard-173(Fix) - Made changes with Appointment Booking Form to clear the input values OnClick of Book Appointment Button

- admin/src/components/lab_components/LabTable.jsx
- admin/src/components/login_components/Login.jsx
UI CARD: Given some space between = Employee MAP Button & Create Service button
> NOVACARD-177

- admin/src/components/access_management/AccessManagement.js
Added these functionalities to the Access Management: By Default Owner is allowed to these functionalities and are hidden on the UI
Import inventory
Used inventories
Login Logout
> NOVACARD-178-ByDefault_Functionalities_for_Owner

- admin/src/App.js
- admin/src/components/bulk_appointments/BulkAppointments.js
Bulk Appointments Added navigation bar
> NOVACARD-177 Bulk Upload

- admin/src/components/access_management/AccessManagement.css
- admin/src/components/access_management/AccessManagement.js
**Added new buttons for below access:
DO NOT SHOW:** Todays Earnings, Total Earnings
**SHOW :** Total Appointments, Todays appointment, Total count, LAB Name, Owner Name & Status Inventory Item name, Total items, Used items, Stock items.
> NOVACARD-171-Access Permission for Dashboard for Employee

- admin/src/components/ems_components/Ems.css
- admin/src/components/ems_components/Ems.js
Novacard 180 - EMS Buttons with working functionalities
Export CSV button is working and downloading csv file. Also given calendar from date to To date
Renamed as Punch-in/out
Create new button for New Employee
> NOVACARD 180 - EMS Buttons with working functionalities

- admin/src/App.css
- admin/src/App.js
Move from Nav to Header - Profile > under > Sign-out
Description
Move from Navigation to Header:
Profile >
Sign-out should come under Profile
> NOVACARD-187-Nav-to-Header

- admin/src/components/bulk_appointments/BulkAppointments.css
- admin/src/components/bulk_appointments/BulkAppointments.js
NOVACARD-193-Bulk-Upload-Design
> NOVACARD-193-Bulk-Upload-Design

- admin/src/App.js
> NOVACARD-199-Deleted

- admin/src/components/access_management/AccessManagement.js
NOVACARD-198-Permission-Button-Alignments DONE
> NOVACARD-198-Permission-Button-Alignments

- admin/src/components/Dashboard_Components/Dashboard.js
- admin/src/components/consumers_appointments/LabTestResultsEntry.css
- admin/src/components/consumers_appointments/PatientPastAppointments.js
PastAppointments.map error is fixed. Dashboard alignment issues fixed.
> PastAppointments.map error is fixed. Dashboard alignment issues fixed.

- admin/src/components/consumers_appointments/AppointmentCard.js
Appointment Cards alignment Issue has been fixed.
> Appointment Cards alignment Issue has been fixed.

- admin/src/components/IMS/Ims.js
NOVACARD-203-IMS_Edit_Buttons are working fine with popup form
> NOVACARD-203-IMS_Edit_Buttons

- admin/src/components/consumer_components/consumermodule.jsx
Upload Aadhar Photo API Integration Is Done
> Upload Aadhar Photo API Integration Is Done

- admin/src/components/lab_components/AvailableServices.js
- admin/src/components/lab_components/Suummary.js
Made LabId dynamic with the API's in Suummary and AvailableServices component
> Made LabId dynamic with the API's in Suummary and AvailableServices components.

- admin/src/components/ems_components/Ems.js
- Added "Last Name" column
- Shifted "Address" column to ending
> NOVACARD-212-Solved-issue

- admin/src/components/IMS/Ims.js
- admin/src/components/consumer_components/consumermodule.jsx
- admin/src/components/ems_components/Ems.js
- admin/src/components/lab_components/LabTable.jsx
- admin/src/components/promotions_offers/Createpromotions.js
Added S.No column in consumer account and made alignment
> Added S.No column in consumer account and made alignment

- admin/src/components/ems_components/Ems.js
Admin Will not be able to see Consumer Accounts on EMS screen.
> Admin Will not be able to see Consumer Accounts on EMS screen.

- admin/src/App.css
- admin/src/App.js
Added FirstName & LastName under profile > Below profile photo
I am fetching data from Session
> NOVACARD-222 - Added FirstName & LastName under profile

- admin/src/components/lab_components/AvailableServices.js
Under Services > GST price should is now roundup FROM ₹43.199999999999996 this  TO ₹43.20
**> Issue Resolved > Ticket Resolved
> Screenshot attached for this Ticket in the JIRA**
> NOVACARD-221

- admin/src/components/consumers_appointments/ExistingAccountSearch.js
NOVACARD-214  Created a consumer account button in Appointment  Booking screen
> NOVACARD-214  Created a consumer account button in Appointment  Booking screen

- admin/src/components/consumer_components/consumermodule.jsx
Now the form will get cleared once user created!
Using this function: cusumerform.resetFields();
> NOVACARD-223-Clear_Consumer_Form_Once_User-Created

- admin/src/components/org_components/OrganizationSummary.jsx
- admin/src/components/org_components/Organizations.js
> OrganizationChanges
